[[constraint]]
  name = "github.com/jenkins-x/jx"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/jenkins-x/golang-jenkins"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "2.0.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "=1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "=1.4.0"

[prune]
  go-tests = true
  unused-packages = true
